
### Register user
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "Victor Olsson",
    "email": "victor@hej.se",
    "password": "hej123",
    "address": "hejgatan 3",
    "zipcode": 12345,
    "city": "Göteborg",
    "phone": "0762336699"
}

### Login user
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "victor@hej.se",
    "password": "hej123"
}

### Get all users
GET http://localhost:3000/api/users

### Gets logged in user from cookie
GET http://localhost:3000/api/login

### Logout user
DELETE http://localhost:3000/api/login




### PRODUCTS ###

GET http://localhost:3000/api/getAllProducts


### PAYMENT ###

POST http://localhost:3000/api/payment/create-payment-intent/
Content-Type: application/json

{
    "username": "Victor",
    "password": "hej123"
}

### ORDERS ###

GET http://localhost:3000/api/getOrders

